export enum Channels {
  PING = 'ping',
  AUTH = 'auth',
  COLORS = 'colors',
  SUPPLIERS = 'suppliers',
  CATEGORIES = 'categories',
  PRODUCTS = 'products',
  PURCHASES = 'purchases',
  PRODUCT_ITEMS = 'product_items',
  INVENTORY = 'inventory',
  CUSTOMERS = 'customers',
  SALES = 'sales',
  EXPENSES = 'expenses',
  TRANSFERS = 'transfers',
  REPORTS = 'reports',
  DASHBOARD = 'dashboard',
  BRANCHES = 'branches',
  PRINT = 'print',
  SYNC = 'sync'
}
